services:
  - type: web
    name: libretranslate
    env: docker
    plan: free
    dockerfilePath: ./docker/Dockerfile
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
    dockerCommand: python3 -m libretranslate --host 0.0.0.0 --port $PORT
